require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "config.ru"
    - "config/puma.rb"
    - "config/boot.rb"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false
